# Generated by Django 5.0 on 2023-12-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dc_degree', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Busy', 'Busy'), ('Leave', 'Leave')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father', models.CharField(max_length=120)),
                ('mother', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('village', models.CharField(max_length=120)),
                ('post', models.CharField(max_length=120)),
                ('police_station', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('ref_by', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=50)),
                ('bed_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cabin', models.CharField(blank=True, max_length=50, null=True)),
                ('b_group', models.CharField(blank=True, max_length=50, null=True)),
                ('times_of_visit', models.IntegerField()),
                ('admit_time', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnh.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('physician_fee', models.IntegerField()),
                ('consultant_fee', models.IntegerField()),
                ('assistant_charge', models.IntegerField()),
                ('dressing', models.IntegerField()),
                ('oxigen', models.IntegerField()),
                ('nebulization', models.IntegerField()),
                ('iv_canula', models.IntegerField()),
                ('cbg', models.IntegerField()),
                ('ecg', models.IntegerField()),
                ('catheter', models.IntegerField()),
                ('enema', models.IntegerField()),
                ('opc', models.IntegerField()),
                ('ot', models.IntegerField()),
                ('delivary_charge', models.IntegerField()),
                ('pathology', models.IntegerField()),
                ('observation_3hrs', models.IntegerField()),
                ('observation_5hrs', models.IntegerField()),
                ('ryles_tube', models.IntegerField()),
                ('suction', models.IntegerField()),
                ('phototherapy', models.IntegerField()),
                ('serv_charge', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bnh.patients')),
            ],
        ),
    ]
