# Generated by Django 5.0 on 2023-12-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0004_alter_bill_assistant_charge_alter_bill_catheter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cbg',
            field=models.IntegerField(default=0, verbose_name='CBG'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ecg',
            field=models.IntegerField(default=0, verbose_name='ECG'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='enema',
            field=models.IntegerField(default=0, verbose_name='Enema Simplex'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='iv_canula',
            field=models.IntegerField(default=0, verbose_name='I\n/V Cannula Charge'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='opc',
            field=models.IntegerField(default=0, verbose_name='Stomach Wash (OPC)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ot',
            field=models.IntegerField(default=0, verbose_name='O.T (Mini)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnh.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rent',
            field=models.IntegerField(default=0, verbose_name='General Seat Rent\n/Cabinet'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='serv_charge',
            field=models.IntegerField(default=0, verbose_name='Service Charge 20%'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vat',
            field=models.IntegerField(default=0, verbose_name='VAT %'),
        ),
    ]
