# Generated by Django 5.0 on 2023-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0005_alter_bill_cbg_alter_bill_ecg_alter_bill_enema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='Paid Amount'),
        ),
    ]
