# Generated by Django 5.0 on 2023-12-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0007_billpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(default=models.CharField(max_length=120), max_length=450, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnh.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnh.item')),
            ],
        ),
    ]
