# Generated by Django 5.0 on 2024-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0008_item_itemcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='assistant_charge',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='catheter',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='cbg',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='consultant_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='delivary_charge',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='dressing',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='enema',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='iv_canula',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='nebulization',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='observation_3hrs',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='observation_5hrs',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='opc',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='ot',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='oxigen',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pathology',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='phototherapy',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='physician_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='ryles_tube',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='suction',
        ),
        migrations.AddField(
            model_name='bill',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=70),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=450, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcount',
            name='unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=40),
        ),
    ]
