# Generated by Django 5.0 on 2024-01-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0010_remove_item_code_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('In Door', 'In Door'), ('Out Door', 'Out Door')], default='In Door', max_length=50),
            preserve_default=False,
        ),
    ]
