# Generated by Django 5.0 on 2024-01-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0011_patient_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='police_station',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ref_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
