# Generated by Django 5.0 on 2024-01-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnh', '0012_alter_patient_district_alter_patient_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='serv_charge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Service Charge 20%'),
        ),
    ]
